spring:
  redis:
    host: 192.168.142.128
    password: 123456
    database: 4
    #    jedis:
    #      pool:
    #        max-active: 8
    lettuce:
      pool:
        max-active: 8
    timeout: 1000
    port: 6379
